### ISSUE TITLE
Performance issue when using "imageNamedRetina:tintColor:" many times.

### ISSUE THREAD

**Issue by pmartel12** [mirego/MCUIImageAdvanced#14]
In one of our projects, the UI freezes when the method `[UIImage(MCRetina) imageNamedRetina:tintColor:]` is used many times.

Version of `MCUIImageAdvanced` used in the project : `1.1.3`

Here is an exemple of the CPU usage of the app when we create a button where `imageNamedRetina:tintColor:` is used four times in the same method:
<img width="1680" alt="stacktrace" src="https://user-images.githubusercontent.com/8106782/45587999-c0fdb080-b8db-11e8-8d9b-2318c711c2fa.png">

With the same code, if `imageNamedRetina:tintColor:` is replaced with `imageNamed:` and the tint colour is applied manually, **we don't have any performance issue**.

After some searches on Google about this issue, I found a [blog post](https://www.hackingwithswift.com/articles/81/how-to-find-and-fix-slow-code-using-instruments) about "how to fix slow code" that talks about a similar problem when `CUIMutableStructuredThemeStore` is used (the call on the highlighted row in the stack trace screenshot). It may be a hint to correct the issue! 😄 

Note: there is no performance issue with version `1.0.1` of `MCUIImageAdvanced`!

**Comment by flambert** [comment]
Don't use it?

**Comment by flambert** [comment]
> Note: there is no performance issue with version 1.0.1 of MCUIImageAdvanced!

That is because version 1.0.1 does not tint the multiple variations of the image and can result in the wrong image being used when the trait collection change.

**Comment by flambert** [comment]
Won't fix
